### ISSUE TITLE
maxdate not working

### ISSUE THREAD

**Issue by DominicBoettger** [SimeonC/sc-date-time#46]
Hello.

I tried to use maxdate with material, but it did not work for me. Model changes and everything else is working fine. Just min and max are not working.

$scope.maxDate = new Date();

``` html
<time-date-picker autosave ng-model="toDate" maxdate="{{maxDate}}" display-mode="full"></time-date-picker>
```

I tried it via attributes and via the configuration option

``` js

analyicsModule.value('scDateTimeConfig', {
    defaultTheme: 'material',
    autosave: false,
    defaultMode: 'date',
    defaultDate: undefined, // should be date object!!
    displayMode: undefined,
    maxdate: new Date(),
    defaultOrientation: false,
    displayTwentyfour: true,
    compact: false
});

```

**Comment by ogrimator** [comment]
Hi,

The issue here is that scDateTime directive will not evaluate your `{{maxDate}}` and instead of value of `maxDate` a string `{{maxDate}}` will be sent. A perfect solution would be that maxdate should be able to use date object, but  what it is expecting is a string describing time. I hope that this can be fixed in later version. Almost all optional values are said to be sting in documentation, which I think is not a good idea for a calendar directive.
