### ISSUE TITLE
Translation demo 

### ISSUE THREAD

**Issue by anakinsolo** [SimeonC/sc-date-time#55]
Hello

Is there a demo for the translation of the sc-date-time ? I dont understand, if I override the default value, should I lose the english version ?

**Comment by Reedyseth** [comment]
@anakinsolo yes you will lose the English version, that is the purpose of the settings.

The bad thing is that the calendar is not fully i18n, cause you can only translate some parts of it, not all, since the week day and month are get from the `Date()` function. They should be define in an array to have full control of the transalation, so, an enhancement :(
